### ISSUE TITLE
grammar

### ISSUE THREAD

**Issue by Saverio976** [romainpanno/liber#8]
https://github.com/romainpanno/liber/blob/096561c7262a6b8a38790913550fd5758f4f5290/README.md?plain=1#L26
waring -> warning

https://github.com/romainpanno/liber/blob/096561c7262a6b8a38790913550fd5758f4f5290/README.md?plain=1#L85
for update -> to update

sorry 😢

**Comment by romainpanno** [comment]
Thanks for the issue 😭
